name: Unit tests
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*' # semver, will override latest
      - '*-preview' # preview, won't override latest
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_type:
        description: "major|minor|patch"
        default: "patch"
        required: true
      release_version:
        description: "Optional release version, e.g. 0.0.1"
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run coverage # later will be moved into dagger
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...