name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run coverage # later will be moved into dagger
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...